export const SIGNUP_USER = "SIGNUP_USER"
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGGEDIN_USER = "LOGGEDIN_USER";
export const LOGGEDOUT_USER = "LOGGEDOUT_USER";
export const GOOGLESIGNUP_USER = "GOOGLESIGNUP_USER"
export const RESET_PASSWORD_USER = "RESET_PASSWORD_USER"
