export const SIGNUP_USER = "SIGNUP_USER"
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGGEDIN_USER = "LOGGEDIN_USER";
export const LOGGEDOUT_USER = "LOGGEDOUT_USER";
export const GOOGLESIGNUP_USER = "GOOGLESIGNUP_USER"
export const RESET_PASSWORD_USER = "RESET_PASSWORD_USER"

export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const READ_PRODUCTS = "READ_PRODUCTS"
export const DELETE_PRODUCTS = "DELETE_PRODUCTS"
export const EDIT_PRODUCTS = "EDIT_PRODUCTS"


